/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pooja Narasimhan
 */
 
public class ManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerWorkAreaJPanel
     */
  private JPanel container;
    private UserAccount account; 
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
   
   
    
    public ManagerWorkAreaJPanel(JPanel container,UserAccount account,Organization organization,Enterprise enterprise,EcoSystem system) {
        
        initComponents();
        this.container = container;
        this.account = account;
        this.system = system;
        this.organization = organization;
        this.enterprise = enterprise;
       
        populateTable();
    }
public void populateTable(){
    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                            dtm.setRowCount(0);
    for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if(o.getName().equals("Manager Organization")) {
             for(WorkRequest wr: o.getWorkQueue().getWorkRequestList() )  {
                  Object row[] = new Object[5];
            row[0] = wr;
            row[1] = wr.getSender();
            row[2] = wr.getType();
            row[3] = wr.getRequestDate();
            row[4] = wr.getStatus();
            dtm.addRow(row);
             }
            }
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Assign = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Type", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Assign.setText("Assign");
        Assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Assign))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Assign)
                    .addComponent(jButton1))
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignActionPerformed
        // TODO add your handling code here:
        int rowSelected = jTable1.getSelectedRow();
        if(rowSelected<0){
            JOptionPane.showMessageDialog(this, "Select a row");
            return;
        }
        WorkRequest wr =(WorkRequest) jTable1.getValueAt(rowSelected, 0);
        if(wr.getType().equals("Technicians Organization")){
            for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(o.getName().equals("Technicians Organization")){
                    wr.setStatus("Assigned to Technicians");
                    o.getWorkQueue().getWorkRequestList().add(wr);
                    JOptionPane.showMessageDialog(this, "Assigned to technician");
                    populateTable();
                    
                }
                
            }
        }
        
        if(wr.getType().equals("Auditor Organization")){
            for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(o.getName().equals("Auditor Organization")){
                    wr.setStatus("Assigned to Auditor");
                    o.getWorkQueue().getWorkRequestList().add(wr);
                    JOptionPane.showMessageDialog(this, "Assigned to Auditor");
                    
                }
                
            }
        }
    }//GEN-LAST:event_AssignActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assign;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
